### PR TITLE
Add default values to bitnami profile

### PR DESCRIPTION
**Pull request by Callisto13**
I may end up opening this in https://github.com/weaveworks/nginx-profile as I think it is easier for integration tests? idk

### CODE REVIEW

**Review by aclevername — APPROVED** [review]
I think this repo is the main example repo so here makes sense

**Comment by aclevername** [comment]
@Callisto13 you going to cut a new tag, or re-cut over older tags?

**Comment by Callisto13** [comment]
no idea 🤷‍♀️  which is preferred?

**Comment by aclevername** [comment]
> no idea  which is preferred?

I guess this is an extension of the profile spec, not a change in spec. So a new tag makes sense

**Pull request merged**
